### ISSUE TITLE
CI workflow doc

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox-docs#18]

**Comment by sanderson** [comment]
CI server bootstrap script:

`sudo bash -c "$(curl -fsSL https://s3.amazonaws.com/tools.nanobox.io/bootstrap/ci.sh)`

**Comment by danhunsaker** [comment]
Of course, don't forget to add another `"` at the end - somehow the copy-pasta missed it.

**Comment by sanderson** [comment]
Automate nanobox login by including the `NANOBOX_USERNAME` and `NANOBOX_PASSWORD` environment variables in the CI server.
