### ISSUE TITLE
Extra_steps is missing some documentation

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-docs#22]
`extra_steps` is documented [multiple](https://github.com/nanobox-io/nanobox-docs/blob/3fc54c85cf8f177c62cf957f907269b390aa8f91/source/app-config/build-deploy-hooks.html.md.erb#L18) [times](https://github.com/nanobox-io/nanobox-docs/blob/3fc54c85cf8f177c62cf957f907269b390aa8f91/source/boxfile/run-config.html.md#extra-steps) for the `run.config` portion of the boxfile, but it [exists in the `deploy.config`](https://github.com/nanobox-io/nanobox-docker-build/blob/95b7b93e14838a3e4aad711b6d59717a25c29620/files/opt/nanobox/hooks/compile#L90) node as well, and should be documented.

If you are needing an example, my use case for needing it was to copy assets into my 'build' prior to deploying a golang app. I originally used `runtime.config.extra_steps` but found that a step somewhere would "Cleaning up any previous releases" and undid my copy. After looking through the build hooks and finding `deploy.config`'s `extra_steps`, the copied files persisted.

>boxfile.yml (working)
>```
>deploy.config:
>  extra_steps:
>    - cp -r $CODE_DIR/app $APP_DIR/app # Move static files into 'build'
>```
**Note:** The `CODE_DIR` and `APP_DIR` variables may only be present in the golang engine at this time

**Comment by sanderson** [comment]
Resolved in eca12f3c511f3a3c3df7afa764590e50d916d5b2
