### ISSUE TITLE
'Enable CI' is no longer required

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-docs#29]
[This page](https://docs.nanobox.io/workflow/ci-cd/#enable-ci-mode) shows how to enable ci mode, but the ci script is already doing it. This part of the instructions can be removed.

![image](https://user-images.githubusercontent.com/2653109/27340165-ffa7227a-5596-11e7-9b8e-90b515691e1c.png)

**Comment by sanderson** [comment]
It's possible that somebody could be using nanobox in a CI workflow without the CI-bootstrap script, so this is still pertinent. The last sentence is meant to clarify when this is needed: _"This is done automatically if using the CI bootstrap script"_. But I may push that to the begging of the paragraph to avoid confusion.

**Comment by glinton** [comment]
Oh good point. I need to read all those letter things ;)
