### ISSUE TITLE
Document the 'hook_timeout'

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-docs#32]
The hooks are configured to [use it as a timeout setting](https://github.com/nanobox-io/nanobox-hooks-code/blob/1221de7f95073cac3c330c6657ee3b7cb2a7a64d/src/lib/engine.rb#L58), but it is unclear how to configure it.

It seems to be configured as follows:
```yml
deploy.config:
  hook_timeout: 300
```
(Where `300` is the number of seconds before timing out)

(Tested on a long running `transform` hook and it seemed to work.)

**Comment by sanderson** [comment]
Thanks Greg. We had this in the docs before, but the timeout wasn't actually being applied so it was removed and put on the backburner. Is this setting now actually being used? Did you try with any value other than `300`?

**Comment by glinton** [comment]
I didn't try with any other values, just without it (default was 60) and my hooks timed out, but since adding it, they haven't timed out. Also, looking at the code, the timeout will apply to the `before|after_live` hooks as well

**Comment by sanderson** [comment]
Cool, I'll add it back to the docs. Are the hooks expecting `deploy_hook_timeout` or `hook_timeout`?

**Comment by glinton** [comment]
it's in the middle of being changed to simply `hook_timeout`

**Comment by sanderson** [comment]
Ok, will you let me know once the change is final? Thanks.

**Comment by sanderson** [comment]
Resolved with eca12f3
