### ISSUE TITLE
Document step-by-step cli install instructions

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-docs#40]
From @saun4app's issue on nanobox: nanobox-io/nanobox/issues/498
>I am suggesting is to show step-by-step of the entire nanobox install process to all users, even though, the actual download is for registered users only.

**Comment by sanderson** [comment]
At this point, we still want to keep the installer download behind a login for the following reason:

There are still issues that crop up that we need to reach out to users to help address. While these are getting fewer and father between, they still happen. With the download behind the dashboard, we're able to associate user accounts with nanobox installs and reach out to users if/when major issues arise.

We will likely move the download out of the dashboard in the future, but for short term bug squashing, we're going to keep it where it is. If a user doesn't want their current install associated with their user account, they can run the following after installing Nanobox:

```bash
nanobox config set anonymous true
```

However they will still need to go through the cli auth process to interact with live, deployed apps.

**Comment by glinton** [comment]
I think he was just asking for documentation of the installation process. I was imagining after downloading from the dashboard
```
dpkg -i nanobox.deb
nanobox run
```
would essentially be the 'process' i think he was wanting to see
